GitHub: webhook with user handler
ocurrent/ocurrent pull request #377
Opened 2022-09-22 15:28 UTC by maiste

This PR addresses #376. The goal is to allow users to use their handler with webhook as the default one is tight to CI behaviours.

2022-09-23 12:57 UTC, tmcgilchrist commented
Rather than adding a new api function, expose the default handler as a function and the function to provide a handler which defaults to using this function. eg

``` ocaml
val default_handler : ....

val webhook_with_handler : ?(handler = default_handler) ...
```

Clearly this breaks the current API version and it should be called out in the [CHANGES.md](https://github.com/ocurrent/ocurrent/blob/master/CHANGES.md) file.

2022-09-23 12:58 UTC, tmcgilchrist requested changes
Please consider the requested API changes.

2022-09-23 13:07 UTC, maiste commented
The reason I was considering adding a new function was to extend the API and don't break the old one with `webhook` as it is used in various projects...

 In this case shouldn't we the API compatible with older versions?

2022-09-26 03:57 UTC, novemberkilo commented
I'm not sure if this is what @tmcgilchrist meant but perhaps we can keep the existing API by just doing:

```
val default_handler : ....

val webhook : ... ?(handler = default_handler) ...
```

So we would only introduce an optional argument to the existing `webhook` function that will default to default_handler. If I am following along correctly then this will not add any new functions to the API, retain backward compatibility, and also provide the ability for a handler to be supplied by a user of `webhook`

2022-09-28 11:59 UTC, maiste commented
As this might not be required, should I keep the version with no breaking change or introduce the one with a breaking change but keep this PR opens as a draft until we figure out if it's needed?

2022-09-28 12:34 UTC, MisterDA commented
IMO it's mostly ok to break the API if you submit PRs to all user, which we _can_ do because we're the users. And I've been doing that quite often.

2022-11-07 14:36 UTC, maiste commented
Closing. See #376

2022-11-07 14:36 UTC, closed without merging