Pre release/mdx
ocurrent/ocurrent pull request #405
Opened 2023-02-06 18:45 UTC by maiste

This PR deactivates `mdx` tests until we figure out why the tests are creating a timeout. They will be reactivated as soon as we have released the `0.6.4` version.

My first version tried to move to `mdx.0.3` stanza, but it didn't solve the issue. Then I tried only to disable the test on `MacOS`, but, unfortunately, I reached this bug with dune (https://github.com/ocaml/dune/issues/6938). The final version comments the tests.

2023-02-06 19:00 UTC, talex5 commented
> Then I tried only to disable the test on MacOS, but, unfortunately, I reached this bug with dune (https://github.com/ocaml/dune/issues/6938).

The bug there is that the tests are *built* even when disabled, which is a problem if the code only builds on one platform. But that shouldn't apply to MDX, I wouldn't have thought (please add to the bug report if MDX tests still run when disabled).

Disabling failing tests without understanding why they're failing seems like a bad idea. When did the problem start?

2023-02-07 12:34 UTC, maiste commented
> The bug there is that the tests are built even when disabled, which is a problem if the code only builds on one platform. But that shouldn't apply to MDX, I wouldn't have thought (please add to the bug report if MDX tests still run when disabled).

On the `OCaml-ci` MacOS worker, they seemed stuck in the `mdx` infinite loop we had in #384. It has the same behaviour as when there was no `enabled_if`. I don't have access to a `Mac` computer to test that locally, however...

> Disabling failing tests without understanding why they're failing seems like a bad idea. When did the problem start?

I agree. It was only to do the release and reactivate them afterwards. This issue is the same as the one mentioned in #384: `mdx` is stuck before timing out with the `git submodule` test.

From an offline discussion with @tmcgilchrist, I will try to rewrite the `mdx` test with `Alcotest` to ensure we keep the same coverage.

2023-02-08 11:00 UTC, emillon commented
FYI, I'm seeing timeouts on opam-repo-ci too. This is likely dependent on the version of the `git` binary used.

2023-02-08 11:52 UTC, maiste commented
Thanks, @emillon, for the follow-up.
My goal by rewriting it using `alcotest` is to be able to set a time lower than 1 hour. This way, even if it fails because of the `git` version, we won't have to wait this time to detect the error.

2023-02-09 09:18 UTC, maiste commented
The tests have been rewritten in `Alcotest`. This way, we won't suffer from any outside issues that could be caused by `mdx` . If we are stuck again in the `Timeout` issue, it will fail in __2 minutes__ instead of __1 hour__, making it easier to test.

This PR needs to be merged before being able to release `0.6.4`.

2023-02-09 14:55 UTC, MisterDA requested changes
Thank you Etienne, it's a faithful rewrite of the mdx code.

2023-02-09 14:55 UTC, MisterDA commented on plugins/git/test/git_test.ml
> +    let cmd = [ "mkdir"; "-p"; dir ] in
```suggestion
    let cmd = [ "mkdir"; dir ] in
```

The original script doesn't use `-p`.

2023-02-09 14:55 UTC, MisterDA commented on plugins/git/test/git_test.ml
> +    [ "commit"; "-q"; "-a"; "-m"; "'Initial submodule commit'" ]
```suggestion
    [ "commit"; "-q"; "-a"; "-m"; "Initial submodule commit" ]
```
Quotes were used for the shell, they should be removed.

2023-02-09 14:55 UTC, MisterDA commented on plugins/git/test/git_test.ml
> +    [ "commit"; "-q"; "-a"; "-m"; "'Remove submodule'" ]
```suggestion
    [ "commit"; "-q"; "-a"; "-m"; "Remove submodule" ]
```
Same.

2023-02-09 14:55 UTC, MisterDA commented on plugins/git/test/git_test.ml
> +  Cmd.git_with ~cwd ~path:"newsub" [ "commit"; "-q"; "-a"; "-m"; "'sub2" ]
```suggestion
  Cmd.git_with ~cwd ~path:"newsub" [ "commit"; "-q"; "-a"; "-m"; "sub2" ]
```

2023-02-23 17:09 UTC, MisterDA approved these changes

2023-02-24 09:34 UTC, maiste commented
The MacOS worker seems to have a struggle with finding `pkg-conf`.  Should we consider [this](https://ci.ocamllabs.io/github/ocurrent/ocurrent/commit/38c42b983238cdc0b9bc00ef7e889dc62095281c/variant/macos-homebrew-5.0.0_arm64_opam-2.1#L627-627) as an `ocurrent` issue or a MacOS worker one?

We can consider merging this PR if it's not a MacOS one.

2023-02-27 09:58 UTC, merged